#!/usr/bin/env bash
#
# Generates docs/tag-catalog.md from the define_elements! table in src/elements/mod.rs.
#
# Port of Winged-Swift/Scripts/generate-tag-catalog.sh, whose best idea is that
# documentation drift is a build break: --check makes CI fail when the checked-in catalog
# no longer matches the source.
#
# One bug is fixed in the port. The Swift generator matches `public class [A-Za-z]+:
# HTMLTag`, which rejects digits, so H1 through H6 are silently missing from its catalog.

set -euo pipefail

cd "$(dirname "$0")/.."

CATALOG="docs/tag-catalog.md"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

generate() {
  cat <<'HEADER'
# Tag catalog

Generated by `scripts/generate-tag-catalog.sh`. **Do not edit by hand** — run the script
instead. `scripts/verify.sh` fails when this file is out of date.

| Constructor | Tag | Void | Whitespace-sensitive |
| --- | --- | :-: | :-: |
HEADER

  # The table entries look like `name => "tag",`, one per line.
  grep -oE '^\s{4}[a-z_0-9]+ => "[a-z0-9]+",' src/elements/mod.rs \
    | sed -E 's/^[[:space:]]+//; s/,$//' \
    | while IFS= read -r line; do
        name="${line%% =>*}"
        tag="${line##*=> }"
        tag="${tag//\"/}"

        void="—"
        case " area base br col embed hr img input link meta source track wbr " in
          *" $tag "*) void="✓" ;;
        esac

        ws="—"
        case " pre code textarea " in
          *" $tag "*) ws="✓" ;;
        esac

        printf '| `%s()` | `<%s>` | %s | %s |\n' "$name" "$tag" "$void" "$ws"
      done

  cat <<'FOOTER'

## Typed constructors

Shapes that carry a required or defaulted argument, and so do not fit the table above.

| Constructor | Produces |
| --- | --- |
| `link_to(href)` | `<a href="…">` |
| `image(src, alt)` | `<img src="…" alt="…">` — `alt` is required |
| `script_src(src)` | `<script src="…">` |
| `stylesheet(href)` | `<link href="…" rel="stylesheet">` |
| `button_typed(type)` | `<button type="…">` |
| `input_named(type, name)` | `<input type="…" name="…">` |
| `label_for(id)` | `<label for="…">` — `for` is a Rust keyword |
| `iframe_titled(src, title)` | `<iframe …>` — `title` is required |
FOOTER
}

mkdir -p docs

if [ "$CHECK" -eq 1 ]; then
  TEMP="$(mktemp)"
  trap 'rm -f "$TEMP"' EXIT
  generate > "$TEMP"

  if [ ! -f "$CATALOG" ]; then
    echo "error: $CATALOG does not exist. Run scripts/generate-tag-catalog.sh." >&2
    exit 1
  fi

  if ! diff -u "$CATALOG" "$TEMP"; then
    echo >&2
    echo "error: $CATALOG is stale. Run scripts/generate-tag-catalog.sh." >&2
    exit 1
  fi

  echo "$CATALOG is up to date."
else
  generate > "$CATALOG"
  echo "Wrote $CATALOG ($(grep -c '^| `' "$CATALOG") entries)."
fi
